% Startup code should be run at the beginning. 
% This code is to include all the directories (set path). 

cd utils
p = strcat(ROOTDIR,                                   ...
           {                                          ...
            '',                                       ...
            'models',                                 ...
            ['models', filesep, 'disColA'],           ...
            'nmpc',                                   ...
            'predictor',                              ...
            'utils',                                  ...
           }, pathsep);
addpath([p{:}]);


% windows path
if (ispc)
    addpath('C:\Data\work\casadi-matlabR2014b-v3.1.0-rc1');
end
% linux path
if(isunix)
end
clear p;
cd ..
